# Generated by Django 3.2.6 on 2021-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticWeb', '0002_car_cardb_flight_flightdb_help_hoteldb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldb',
            name='hotel_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
