# Generated by Django 3.2.6 on 2021-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticWeb', '0003_alter_hoteldb_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdb',
            name='depart_airport',
            field=models.CharField(default='jkia', max_length=100),
            preserve_default=False,
        ),
    ]
