# Generated by Django 3.2.6 on 2021-08-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcticWeb', '0004_flightdb_depart_airport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='Location',
            new_name='Airport',
        ),
    ]
