# Generated by Django 3.2.6 on 2021-10-11 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arcticWeb', '0005_rename_location_flight_airport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardb',
            options={'ordering': ['-update_time']},
        ),
        migrations.AddField(
            model_name='cardb',
            name='update_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
